# Generated by Django 4.2.5 on 2025-05-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0003_alter_tweet_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="tone",
            field=models.CharField(
                choices=[
                    ("neutral", "Neutral"),
                    ("toxic", "Toxic"),
                    ("non-toxic", "Non-Toxic"),
                ],
                default="neutral",
                max_length=10,
            ),
        ),
    ]
