# Generated by Django 4.2.5 on 2025-06-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0007_remove_tweet_like_count_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
