# Generated by Django 4.2.5 on 2025-06-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0008_tweet_like_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="like_count",
        ),
    ]
